### ISSUE TITLE
Is /event-callback missing?

### ISSUE THREAD

**Issue by kallu** [aws-samples/ops-health-ai#1]
Hi,
wanted to test this out and got it ALMOST working to the point where it can post to Slack and update the events, but "Accept event" and "Discharge event" buttons point to API path /event-callback which doesn't exists in API Gateway. It feels like CDK is missing a part that would route /event-callback some lambda or step-function?

E.g. clicking "Accept event" takes me to https://XXXXXXX.execute-api.us-east-1.amazonaws.com/prod/event-callback?status=SUCCESS&taskToken=QVFDVUF...Z20z

<img width="620" alt="Screenshot 2024-10-24 at 18 36 38" src="https://github.com/user-attachments/assets/729cbb02-1954-4d48-9dbc-e3f6d3840f9d">

**Comment by awseanxw** [comment]
Thanks for submitting the issue. I did not include the 'callback' endpoint as part of the stack as it was meant for the manual way to react on events, which is redundant in the AI-powered solution scope where the whole idea was to rely on the AI assistant to react automatically without human intervention (clicking the buttons). That said, you make a good point that this may cause confusions, I shall add the endpoint shortly and update README that 'clicking of the buttons' is only required when a "manual reaction" needs to happen as a fallback. Please stay tuned. Thanks.

**Comment by awseanxw** [comment]
Latest commit included the callback endpoint as part of the deployment stack. README - test section updated as the following:
...
You will receive Slack messages notifying you about the mockup event and then followed by automatic feedbacks by the AI assistant after a few seconds. You do NOT need to click the “Accept” or “Discharge” buttons included in the message, these buttons are only useful when AI assistant failed to acknowledge the event, they are used as a fallback mechanism for human user to intervene.
